### ISSUE TITLE
Only the top part of the SuRVoS window appears

### ISSUE THREAD

**Issue by wisbaum** [DiamondLightSource/SuRVoS#112]
I see only the top part of the SuRVoS window.

I'm running the program on a server with a heavy GPU, and X forwarding to my laptop (Manjaro linux). When the display text scaling is set to 100% it works as expected and opens up to the full display size, but the rest of the desktop text is unreadable (2560x1440 pixels on a 14" screen). When the text scaling is at 200% the survos window is in portrait mode and the bottom gets cut off.

**Comment by OllyK** [comment]
Apologies for the slow reply @wisbaum. We are no longer making changes to this relase of SuRVoS, so unfotunately I'm unable to help you with your problem. I hope you've found a way to get around it,
Best Wishes
