### ISSUE TITLE
SuRVoS does not report `+ Ready` in console upon exporting raw data

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [DiamondLightSource/SuRVoS#114]
Dear all,

SuRVoS does not report `+ Ready` in console upon exporting raw data as it does while exporting e.g. raw annotations.

```
+ Loading data into memory
 * Writing file [.../emd-1181/survos_export\data.h5]
```

A file appears on the hard drive, but is it written "completely"?

Best regards,
Aliaksei

**Comment by OllyK** [comment]
Hi Aliaksei, 
Thanks for your message. The file should be written correctly even if `+Ready` isn't reported. If you have any issues with corrupted files let us know. Unfortunately we're not making changes to this version of SuRVoS any longer, so I'm unable to make a change to the output logging at this time. I will close your issue as I assume there isn't a problem with opening saved files.
Best Wishes.
