### ISSUE TITLE
Installing clarification

### ISSUE THREAD

**Issue by tstarborg** [DiamondLightSource/SuRVoS#26]
Please can you clarify that you need Python 2 when installing Anaconda in your instructions for Linux users?

As I only half understand python I had a few issues following the instructions at (https://diamondlightsource.github.io/SuRVoS/docs/installation/).
The link to Anaconda offers two version of Python (currently 3.4 and 2.7).  It wasn't clear from the instructions on your site that you'd coded in Python 2.  Seeing as how the bigger number is better in my mind I spent quite a lot of time trying to force your code to work with python 3.4.  It was only after I found a few print errors (expecting parentheses) that I realised that the Python version affected the syntax of quite a few commands.

I think I have it working now (don't mention the problems I had getting Cuda running on Centos).

I'd have emailed this as its not really a coding error, but there are no links in your instructions (unless email@domain.com is a real person https://diamondlightsource.github.io/SuRVoS/about/)

Hope this is helpful.

Toby S

**Comment by imaluengo** [comment]
Hi @tstarborg,

Thanks for the comments. It is indeed python 2.7 the one used in SuRVoS (although it will be compatible with both in the future). Sorry for missing that comment in the installation instructions. It is already fixed, along with an email for the contact page.

Thank you for your interest,
Imanol
