### ISSUE TITLE
SuRVoS doesn't compile on OSx

### ISSUE THREAD

**Issue by bertinets** [DiamondLightSource/SuRVoS#31]
I've recently learned about SuRVoS and I'd like to test it to process 3D stacks obtained through FIB serial slicing but I have an issue when I try to compile the software on OS X.

System details:

- OSx 10.12.3
- python 2.7.12 (homebrew)
- clang "Apple LLVM version 8.0.0 (clang-800.0.42.1)"
- nvcc "Cuda compilation tools, release 8.0, V8.0.61"

At first, I could not build it because the script would look for cud/lib64, which is not in the OS X version of the coda installation. After symbolic linking cuda/lib64 to cuda/lib, the   
`python setup.py build_ext -i`

proceeded for a while, until I got the following (3) errors:

```
In file included from /opt/SuRVoS/survos/lib/qpbo_src/QPBO.cpp:918:
/opt/SuRVoS/survos/lib/qpbo_src/instances.inc:14:25: error: explicit specialization of 'get_type_information' after instantiation
        inline void QPBO<int>::get_type_information(const char*& type_name, const char*& type_format)
                               ^
/opt/SuRVoS/survos/lib/qpbo_src/QPBO.cpp:293:2: note: implicit instantiation first required here
        get_type_information(type_name, type_format);
        ^
In file included from /opt/SuRVoS/survos/lib/qpbo_src/QPBO.cpp:918:
/opt/SuRVoS/survos/lib/qpbo_src/instances.inc:21:27: error: explicit specialization of 'get_type_information' after instantiation
        inline void QPBO<float>::get_type_information(const char*& type_name, const char*& type_format)
                                 ^
/opt/SuRVoS/survos/lib/qpbo_src/QPBO.cpp:293:2: note: implicit instantiation first required here
        get_type_information(type_name, type_format);
        ^
In file included from /opt/SuRVoS/survos/lib/qpbo_src/QPBO.cpp:918:
/opt/SuRVoS/survos/lib/qpbo_src/instances.inc:28:28: error: explicit specialization of 'get_type_information' after instantiation
        inline void QPBO<double>::get_type_information(const char*& type_name, const char*& type_format)
                                  ^
/opt/SuRVoS/survos/lib/qpbo_src/QPBO.cpp:293:2: note: implicit instantiation first required here
        get_type_information(type_name, type_format);
        ^
```
Do you have any hint about this or it simply cannot run on OS X?

I've tried also on another system (OS X 10.11.3) with apple clang 7.3.0 and I got the very same errors. On the same system with a clang obtained through homebrew (3.9) I get an error from nvcc, as the 3.9 version of clang is not supported by the cuda compiler driver.

**Comment by polarise** [comment]
I get the same. Any chance this will be fixed soon?

**Comment by srikanthnagella** [comment]
Fixed in the master branch
