### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by MattPankhurst** [DiamondLightSource/SuRVoS#32]
Hi there,
SuRVoS crashes when I load a file. It's a 3D .tiff. It is 1450x1450x1198 and 16 bit.
Does SuRVoS have an upper limit for file size?
Any suggestions much appreciated.
Thanks,
Matt

**Comment by srikanthnagella** [comment]
Hi Matt,
It should work upto 1024x1024x1024. You could try resizing the images to this size.
Sri

**Comment by srikanthnagella** [comment]
Please reopen this if needed.
