### ISSUE TITLE
scikit-tensor dependency issues

### ISSUE THREAD

**Issue by jewettaij** [DiamondLightSource/SuRVoS#36]
There are several problems with the scikit-tensor module which SuRVoS depends on:

1) scikit-tensor does not appear to be python3 compatible.  For example, when I install it from within a virtual environment (created using "python3 -m venv survos_venv"), the error message I get is:
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(mod.__version__)?

2) scikit-tensor appears to be no longer maintained.  

a) The github repository page "https://github.com/mnick/scikit-tensor" is showing a travis build failure.  I can clone this and run "pip install .", and there are no errors during installation, but the fact that it has been failing automatic dependency tests for the last 9 months is disconcerting.

b) If I install scikit-tensor using pip (using "pip install scikit-tensor"), I get the following error:
pkg_resources.DistributionNotFound: The 'nose' distribution was not found and is required by the application.  (Perhaps this is a separate issue.  However I've seen this on 3 different python distributions on different computers running freshly installed versions of ubuntu 16.06 and 18.04)

Are there any alternatives to scikit-tensor?

**Comment by srikanthnagella** [comment]
Please use the pyqt5 branch. master branch is only compatible with python
2.7

**Comment by jewettaij** [comment]
Thanks.
I can confirm that wwitching to the pyqt5 branch and installing via conda gets around this problem.
However, the documentation at 
https://diamondlightsource.github.io/SuRVoS/docs/installation/
needs to be updated.  Here's an excerpt from that web page:
------------------------
With Anaconda:
```
$> conda update conda pip
$> conda install numpy scipy matplotlib scikit-learn scikit-image cython seaborn networkx libgcc pyqt=4.11.4
$> pip install scikit-tensor tifffile
```
With another python distribution:
```
$> pip install --upgrade pip
$> pip install --upgrade numpy scipy matplotlib scikit-learn scikit-image cython seaborn networkx scikit-tensor tifffile
```
I'll close this issue when the documentation is updated (and when the "pyqt5" branch is hopefully merged)
Thanks again

**Comment by srikanthnagella** [comment]
Not relevant anymore. The latest version doesn't depend on this.
