### ISSUE TITLE
Install SuRVoS from conda channel doen't work

### ISSUE THREAD

**Issue by DimitriosBellos** [DiamondLightSource/SuRVoS#45]
I tried installing SuRVoS using the conda channnel by executing the following command:

`conda install -c conda-forge -c numba -c ccpi survos`

However, after the installation when I try to open SuRVOS by typing:

`survos` or `SuRVoS`

The terminal responds that there isn't a command with that name.

Do I miss some steps or to open SuRVoS I have to do something different ?

**Comment by srikanthnagella** [comment]
Fixed: Let me know if the problem exists.
