### ISSUE TITLE
GPU memory issue Windows 10

### ISSUE THREAD

**Issue by ememuri** [DiamondLightSource/SuRVoS#46]
I have recently installed SuRVos on two Windows 10 machines and it is constantly crashing, even when only small data sets are being used (smaller than those I tested SuRVos on when at Diamond). I received the following as an error when computing supervoxels on one of the computers:

[GPU] Selected CUDA device: 0
[GPU] Device 0: "GeForce GTX 1060 6GB" with compute capability .1, 1024 threads pb.
[CUDA ERROR] Memcpy back: an illegal memory access was encountered
QObject: :~Timers cannot be stopped from another thread

Both computers have Python 3.6 and Anaconda3 running on them.

**Comment by srikanthnagella** [comment]
Can you please send me a dataset so that i can replicate the error.

**Comment by srikanthnagella** [comment]
temporary measure is to change the ROI to 64, 128,256,512,1024 cubes.

**Comment by srikanthnagella** [comment]
I have now fixed this bug and uploaded the latest version. Let me know if you encounter anymore bugs.

**Comment by ememuri** [comment]
Hi Sri,

Below is a link to the folder with the data sets and workspace that has
caused the problem. The workspace is the Test_1 folder. However, I have
tried other data sets and have had the same problem so it does not seem to
be data/specific. With the  Test_1 workspace, survos crashes when we try to
calculate the frangi filter or when we try to reduce the size of the
supervoxels. Another error that I have received when computing the frangi
filter is below the link.

Cheers,

Emily Baird

/CT_2/Inga
https://130.235.244.162:8001/portal/apis/fileExplorer/share_link.cgi?link=hzZXA78xFtmRKZ21Ph1OE0



### Computing Feature: frangi ###

### compute_channel ###
+ Loading data into memory
+ Rescaling data
+ Computing feature frangi
+ Computing Hessian Matrix
+ Padding data
   - Computing gaussian (radius=(3, 3, 3))
[GPU] Selected CUDA device: 0
[GPU] Device 0: "GeForce GTX 970" with compute capability 5.2, 1024 threads
pb.
+ Computing Hessian Eigenvalues
[GPU] Reusing device (0) with 1024 threads
.[CUDA ERROR] SRC & KERNEL & DST: out of memory
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by srikanthnagella** [comment]
Ahh. got the problem. your datasets are more than 1024pixels in width / height. SuRVoS - 1 only supports 1024pixel images. you can either resize your datasets or you can select a ROI in the tab and select region. remember that total pixels in each dimensions should be less than 1024pixels.
