### ISSUE TITLE
MegaVoxel Error: "nane '_neighbors' is not defined"

### ISSUE THREAD

**Issue by DimitriosBellos** [DiamondLightSource/SuRVoS#49]
Hello,

I recently have tried to use the MegaVoxel feature however I receive an error window saying:

[NameError]
name '_neighbors' is not defined

![megavoxels_error](https://user-images.githubusercontent.com/34098719/42947220-8313eee4-8b75-11e8-8b45-fd5d4144a13c.PNG)

**Comment by srikanthnagella** [comment]
Which version of Survos and python are you using?

**Comment by DimitriosBellos** [comment]
I am using Anaconda with Python 3.6.4 and SuRVoS 1.1.1

**Comment by DimitriosBellos** [comment]
Is there any development regarding this issue?
