### ISSUE TITLE
to be able to annotate and train after save

### ISSUE THREAD

**Issue by wintun24** [DiamondLightSource/SuRVoS#76]
At the moment, once the tranined and predicted labelling is saved, we cannot do any more annotation or prediction, which means we need to start a new workspace and do it again if we want to make any change after "saved". Would be good if we can do annotation and prediction again (even after saving) and do the new "save" which would rewrite the old "save".

**Comment by wintun24** [comment]
re-train and re-predict (after saved) is ok to do in expt version, but not in current survos.

**Comment by OllyK** [comment]
Will close this since it will be fixed in SuRVoS 1.5
