### ISSUE TITLE
graphs in label splitter and level statistics

### ISSUE THREAD

**Issue by wintun24** [DiamondLightSource/SuRVoS#77]
1. Y axis of graphs (in label splitter) should be number of object. The same applies to the y axis of  graphs in level statistics (the ones from left upper to right lower diagonal). At the moment, y axis label is not accurate, therefore, difficult to understand for the users. 

2. Graphs in label splitter and level statistics are shown in kde format. For users, I think normal histogram is easier to understand and interpret. Suggest to show the graphes in normal histogran (or in subplot that shows both kde form and normal histogram). 

3. Put a pop up explantation box (i.e. screen tips) when putting the cursor/arrow on the graph (so users can understand easily the background maths and the meaning of each graph). At the moment, it is difficult to understand the meaning of each graph.

**Comment by OllyK** [comment]
Points 1 and 2 are addressed by fixes in branch for version 1.5
