### ISSUE TITLE
the name 'size' should be 'vol' in stats and graphs

### ISSUE THREAD

**Issue by wintun24** [DiamondLightSource/SuRVoS#78]
In label splitter and level statistics, the volume of segmented object, bounding box and orientated bounding box are calculated but they are named as size/area. It is misleading for the users. It should be named as 'volume', not 'size/area'.

**Comment by wintun24** [comment]
Again volume is calculated by pixel * pixel * slice number which is not the correct volume actually. The slice number should be changed into pixel value so that the result is in cubic pixel.

**Comment by OllyK** [comment]
Fixed in branch for version 1.5
