### ISSUE TITLE
Problems using recent anaconda

### ISSUE THREAD

**Issue by bersbersbers** [DiamondLightSource/SuRVoS#88]
So I downloaded anaconda3 2019.07 for Windows 10, activated the base environment, installed SuRVoS: had to do some `conda install python==3.6.9 scikit-learn==0.19.0 matplotlib==2.0.2` (Python 3.7 not being supported, SuRVoS requesting RandomizedPCA, and see #86).

So now that it installs, I can run it and open a 3D TIFF which seems to load fine, judging from the dataset preview. Upon loading, I receive a TypeError, however: "Can't broadcase (30, 2048, 2048) -> (2048, 30, 2048). Is that due to package versions as well? If so, which package should I downgrade?

**Comment by OllyK** [comment]
Hi,
Great that you've nearly got it working. The broadcast error isn't a package issue as far as I know. Are you creating an empty workspace folder when you load the data? It looks like the wrong data dimensions are being picked up from somewhere

**Comment by bersbersbers** [comment]
Am I creating an empty workspace folder? Yes, I believe so. I start SuRVoS and select only one single 3D TIFF file.

**Comment by OllyK** [comment]
I can repeat this error only if I:
1. Open a dataset with a certain 3D perspective e.g Axial using a new empty directory for a workspace e.g my_workspace_dir
2. Close SuRVoS
3. Open SuRVoS, -> 'Open Dataset' select the same dataset and change the 3D perspective e.g.  Coronal but select the same workspace as before eg. my_workspace_dir which is not empty
4. When loading I get the error 'Workspace folder is not empty, do you still want to continue? It might overwrite and remove previous files.' If I click'yes ' I get the 'Type Error can't broadcast' problem

So, if you want to change the 3D perspective please create a new empty directory for your workspace, then you shouldn't get this error.

**Comment by bersbersbers** [comment]
I certainly did not change any 3D perspective - I have only ever tried to load the same 3D dataset (without success). But it is working now, so whatever I did wrong the first time, I did it correctly now.
(Maybe I chose %TEMP% as a workspace folder, which is non-empty.)
